{"name": "用户登录=>预期失败", "status": "passed", "description": "该用例是针对 登录失败 场景的测试", "steps": [{"name": "输入账号", "status": "passed", "attachments": [{"source": "8bdeac97-4bad-4695-a35c-403e7974e7b2-attachment.attach"}], "start": 1693481467294, "stop": 1693481467571}, {"name": "输入密码", "status": "passed", "attachments": [{"source": "7af5798a-246f-49d6-89db-75dcf8ffa63e-attachment.attach"}], "start": 1693481467571, "stop": 1693481467719}, {"name": "选择登录角色", "status": "passed", "attachments": [{"source": "6b87ab87-0812-4f60-9a45-015b6203d00d-attachment.attach"}], "start": 1693481467719, "stop": 1693481467804}, {"name": "点击登录", "status": "passed", "start": 1693481467804, "stop": 1693481467911}], "attachments": [{"name": "log", "source": "54e25ebe-a048-4087-8366-6f1e67d0ccea-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'index': '1', 'username': 'admin', 'password': '123', 'role': '管理员'}"}], "start": 1693481467294, "stop": 1693481471533, "uuid": "45f7efd5-6d52-4b28-94e3-175194a1e3f6", "historyId": "929bb59ad01fb7b5a2feb70112a91f13", "testCaseId": "ffae38639f3844393ad1430a7508a601", "fullName": "test_case.test_001_login#test_invalid_login", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "用例--登录--预期登陆失败"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_001_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "A"}, {"name": "thread", "value": "25412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_001_login"}], "links": [{"type": "issue", "url": "http://localhost:8080/", "name": "点击，跳转到登录BUG的链接地址"}]}